name: CI Build Workflow

on:
  push:
    branches: [main, action]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  say-work:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "work"
