name: CI Build Workflow

on:
  push:
    branches: [main, action]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      # Debug informacije
      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -version
          echo "Current directory: $(pwd)"
          echo "Files in root:"
          ls -la
          
      - name: Validate pom.xml
        run: mvn validate
        
      - name: Show effective POM (debug)
        run: mvn help:effective-pom | head -50
        
      # Test sa više debug informacija
      - name: Run unit tests
        run: mvn clean test -e -X
        env:
          MAVEN_OPTS: "-Xmx1024m"
        
      # Prikaži test rezultate čak i ako testovi propadnu
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/test-classes/
            
      - name: Show test failures (if any)
        if: failure()
        run: |
          echo "=== SUREFIRE REPORTS ==="
          find target/surefire-reports -name "*.txt" -exec cat {} \;
          echo "=== END REPORTS ==="

  build:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Build project
        run: mvn clean package -DskipTests